In [3]:
import pandas as pd

df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [13]:
import numpy as np
data=np.random.rand(2,3)
print(data)

[[0.13019017 0.88260887 0.94207384]
 [0.00198647 0.08783702 0.91872511]]


In [16]:
df=pd.DataFrame(data,columns=['a','b','c'] )
print(df)

          a         b         c
0  0.130190  0.882609  0.942074
1  0.001986  0.087837  0.918725


In [25]:
nd =(np.ndarray(shape=(5,2)))
df=pd.DataFrame(nd,columns=['a','b'] )
print(df)

[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 1.06810811e-306]
 [1.89146896e-307 1.37961302e-306]
 [1.05699242e-307 8.01097889e-307]
 [8.45603441e-307 1.78021527e-306]]


In [40]:

nd= np.ndarray(shape=(2,2,3))
print(nd)

print(pd.Panel(nd,items=['a','b']).to_frame())


[[[0.83439339 0.57045051 0.63531767]
  [0.17623619 0.55600687 0.69834958]]

 [[0.03998112 0.48560896 0.91357404]
  [0.51557864 0.58635682 0.55149261]]]
                    a         b
major minor                    
0     0      0.834393  0.039981
      1      0.570451  0.485609
      2      0.635318  0.913574
1     0      0.176236  0.515579
      1      0.556007  0.586357
      2      0.698350  0.551493


C:\Users\akhil\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2963: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


In [44]:
data= {'item1':pd.DataFrame([[5,6,7,7],[0,1,2,3]]),
    
'item2': pd.DataFrame([[1,2,3,3],[0,1,2,3]])}
print(pd.Panel(data).to_frame())
print(pd.Panel(data)['item1'])

             item1  item2
major minor              
0     0          5      1
      1          6      2
      2          7      3
      3          7      3
1     0          0      0
      1          1      1
      2          2      2
      3          3      3
   0  1  2  3
0  5  6  7  7
1  0  1  2  3


C:\Users\akhil\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2963: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


In [46]:
print(pd.Panel(data).major_xs(0))

   item1  item2
0      5      1
1      6      2
2      7      3
3      7      3


C:\Users\akhil\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2963: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


In [48]:
print(pd.Panel(data).minor_xs(0))

   item1  item2
0      5      1
1      0      0


C:\Users\akhil\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2963: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


In [50]:
s=pd.Series([2,7,0,4])
print(s)
print(s.size)
print(s.head(2))
print(s.tail(2))

0    2
1    7
2    0
3    4
dtype: int64
4
0    2
1    7
dtype: int64
2    0
3    4
dtype: int64


In [54]:
print(df)
print(df.T)
print(df)
print(df.axes)
print(df.ndim)
print(df.size)
print(df.values)
print(df.head(1))

               a              b
0  6.230421e-307  4.672967e-307
1  1.691211e-306  1.068108e-306
2  1.891469e-307  1.379613e-306
3  1.056992e-307  8.010979e-307
4  8.456034e-307  1.780215e-306
               0              1              2              3              4
a  6.230421e-307  1.691211e-306  1.891469e-307  1.056992e-307  8.456034e-307
b  4.672967e-307  1.068108e-306  1.379613e-306  8.010979e-307  1.780215e-306
               a              b
0  6.230421e-307  4.672967e-307
1  1.691211e-306  1.068108e-306
2  1.891469e-307  1.379613e-306
3  1.056992e-307  8.010979e-307
4  8.456034e-307  1.780215e-306
[RangeIndex(start=0, stop=5, step=1), Index(['a', 'b'], dtype='object')]
2
10
[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 1.06810811e-306]
 [1.89146896e-307 1.37961302e-306]
 [1.05699242e-307 8.01097889e-307]
 [8.45603441e-307 1.78021527e-306]]
               a              b
0  6.230421e-307  4.672967e-307
