In [21]:
import pandas as pd
import numpy as np

data= {'Name':pd.Series(['a','b','c','d','e','f','g','h','i','j','k']),
       'Age': pd.Series([12,34,23,45,12,23,12,13,14,15,11]),
       'Marks':pd.Series([10,9.2,9.4,9.6,9,2,8,7,3,10.0, 5.5])
      }
index= ["Stu{}".format(str(i)) for i in range(1,12)]
df = pd.DataFrame(data)
print(df)


   Name  Age  Marks
0     a   12   10.0
1     b   34    9.2
2     c   23    9.4
3     d   45    9.6
4     e   12    9.0
5     f   23    2.0
6     g   12    8.0
7     h   13    7.0
8     i   14    3.0
9     j   15   10.0
10    k   11    5.5


In [24]:
print(df.count())
print(df.sum())
print(df.mean())
print(df.median())
print(df.mode())
print(df.std())
print(df.min())
print(df.max())

print(df.prod())

Name     11
Age      11
Marks    11
dtype: int64
Name     abcdefghijk
Age              214
Marks           82.7
dtype: object
Age      19.454545
Marks     7.518182
dtype: float64
Age      14.0
Marks     9.0
dtype: float64
   Name   Age  Marks
0     a  12.0   10.0
1     b   NaN    NaN
2     c   NaN    NaN
3     d   NaN    NaN
4     e   NaN    NaN
5     f   NaN    NaN
6     g   NaN    NaN
7     h   NaN    NaN
8     i   NaN    NaN
9     j   NaN    NaN
10    k   NaN    NaN
Age      11.039598
Marks     2.840006
dtype: float64
Name      a
Age      11
Marks     2
dtype: object
Name      k
Age      45
Marks    10
dtype: object
Age      4.199970e+13
Marks    1.380802e+09
dtype: float64


In [27]:
print(df.cumsum())
print(df.cumprod())


           Name  Age Marks
0             a   12    10
1            ab   46  19.2
2           abc   69  28.6
3          abcd  114  38.2
4         abcde  126  47.2
5        abcdef  149  49.2
6       abcdefg  161  57.2
7      abcdefgh  174  64.2
8     abcdefghi  188  67.2
9    abcdefghij  203  77.2
10  abcdefghijk  214  82.7


TypeError: can't multiply sequence by non-int of type 'str'

In [28]:
print(df.describe())

             Age      Marks
count  11.000000  11.000000
mean   19.454545   7.518182
std    11.039598   2.840006
min    11.000000   2.000000
25%    12.000000   6.250000
50%    14.000000   9.000000
75%    23.000000   9.500000
max    45.000000  10.000000


In [29]:
print(df.describe(include = 'all'))

       Name        Age      Marks
count    11  11.000000  11.000000
unique   11        NaN        NaN
top       g        NaN        NaN
freq      1        NaN        NaN
mean    NaN  19.454545   7.518182
std     NaN  11.039598   2.840006
min     NaN  11.000000   2.000000
25%     NaN  12.000000   6.250000
50%     NaN  14.000000   9.000000
75%     NaN  23.000000   9.500000
max     NaN  45.000000  10.000000


In [39]:
def adder(e1,e2):
    return e1+e2

data=np.random.randn(3,3)
print(data)
df = pd.DataFrame(data, columns= ['a','b','c'])
print(df.pipe(adder,2))

[[ 1.8212702  -0.88252206  0.74492144]
 [ 0.00297158  0.06253071 -1.83566489]
 [ 0.70935547 -0.01185359  0.38305719]]
          a         b         c
0  3.821270  1.117478  2.744921
1  2.002972  2.062531  0.164335
2  2.709355  1.988146  2.383057


In [40]:
print(df.apply(np.mean, axis=1))

0    0.561223
1   -0.590054
2    0.360186
dtype: float64


In [37]:
print(df.pipe(np.mean))

0   -0.646032
1    0.469411
2   -0.318367
dtype: float64


In [38]:
print(df.apply(lambda x : x.max() - x.min()))

0    2.373672
1    2.167949
2    1.151669
dtype: float64


In [45]:
print(df)
print(df['a'].map(lambda x : x*100))
print(df.applymap(lambda x : x*100))

          a         b         c
0  1.821270 -0.882522  0.744921
1  0.002972  0.062531 -1.835665
2  0.709355 -0.011854  0.383057
0    182.127020
1      0.297158
2     70.935547
Name: a, dtype: float64
            a          b           c
0  182.127020 -88.252206   74.492144
1    0.297158   6.253071 -183.566489
2   70.935547  -1.185359   38.305719
